"""Add relationship or new columns

Revision ID: a0db50b5a9a7
Revises: 54f30616485b
Create Date: 2025-03-15 17:25:31.441809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0db50b5a9a7'
down_revision: Union[str, None] = '54f30616485b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('health_parameters_approved_by_fkey', 'health_parameters', type_='foreignkey')
    op.alter_column('reports', 'report_unique_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_reports_report_unique_id'), 'reports', ['report_unique_id'], unique=True)
    op.drop_constraint('reports_client_id_fkey', 'reports', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('reports_client_id_fkey', 'reports', 'users', ['client_id'], ['id'])
    op.drop_index(op.f('ix_reports_report_unique_id'), table_name='reports')
    op.alter_column('reports', 'report_unique_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key('health_parameters_approved_by_fkey', 'health_parameters', 'users', ['approved_by'], ['id'])
    # ### end Alembic commands ###
